###review last work learning

In [69]:
import pandas as pd
import numpy as np
df = pd.read_csv('A_stat_data_112.csv')
df2 = df.copy()
df2.head()

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8373966078912715601,8154604467375388289
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3516683932418412104,3762301478342295221
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-65799051578279613,4652807748946159405
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6293485111595748020,240621445882253268
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4998280410504838977,-3340858198738005072

In [70]:
dfhw = df2
dfhw

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8373966078912715601,8154604467375388289
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3516683932418412104,3762301478342295221
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-65799051578279613,4652807748946159405
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6293485111595748020,240621445882253268
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4998280410504838977,-3340858198738005072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909954,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,5090607127449525741,703618323232836566
1909955,8,04/22 人與鼠的戰爭【環境教育－動物保育】（中階）,易,世界櫥窗,連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,1122720388891184818,8809938774431070893
1909956,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-3633088233029289359,703618323232836566
1909957,8,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-3198336096824660439,-371611706378504607
1909958,9,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,8248998181802054321,-371611706378504607

exercise

In [11]:
print(df2.head())
print(df2.tail(3))
print(df2.index)
print(df2.columns)

   grade                      mission_name mission_difficulty mission_field  \
0      5        05/06 虎姑婆【多元文化教育－傳說故事】（初階）                  易            文學
1      5         05/06 二郎【多元文化教育－傳說故事】（初階）                  中            文學
2      6         05/09 蚩尤【多元文化教育－傳說故事】（初階）                  難            人物
3      5        05/13 狗狗吃便便【環境教育－動物奇聞】（初階）                  中          生活知識
4      6  05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）                  易          自然科學

  mission_type  mission_semester_year mission_semester  \
0           連續                    112            112-2
1           連續                    112            112-2
2           連續                    112            112-2
3          非連續                    112            112-2
4        連續＋圖表                    112            112-2

          mission_datetime_utc8 mission_status  is_completed  ...  \
0  Mon May 06 08:00:00 UTC 2024          已派發任務             0  ...
1  Mon May 06 08:00:00 UTC 2024          已派發任務             0  ...
2  Thu May 09 08:00:00 UTC 2024          已派發任務             0  ...
3  Mon May 13 08:00:00 UTC 2024          已派發任務             0  ...
4  Thu May 16 08:00:00 UTC 2024          已派發任務             0  ...

  answer_duration_sec  mission_answer_count  content_indicator_correct_rate  \
0                 NaN                     0                             NaN
1                 NaN                     0                             NaN
2                 NaN                     0                             NaN
3                 NaN                     0                             NaN
4                 NaN                     0                             NaN

   comprehensive_indicator_correct_rate  explanation_indicator_correct_rate  \
0                                   NaN                                 NaN
1                                   NaN                                 NaN
2                                   NaN                                 NaN
3                                   NaN                                 NaN
4                                   NaN                                 NaN

   extraction_indicator_correct_rate  form_indicator_correct_rate  \
0                                NaN                          NaN
1                                NaN                          NaN
2                                NaN                          NaN
3                                NaN                          NaN
4                                NaN                          NaN

   first_correct_rate              user_id           mission_id
0                 NaN -8373966078912715601  8154604467375388289
1                 NaN  3516683932418412104  3762301478342295221
2                 NaN   -65799051578279613  4652807748946159405
3                 NaN -6293485111595748020   240621445882253268
4                 NaN  4998280410504838977 -3340858198738005072

[5 rows x 22 columns]
         grade                   mission_name mission_difficulty  \
1909956      8  04/22 動物園該存在嗎？【環境教育－動物保育】（中階）                  難
1909957      8           4月特別任務－【SDGs 議題】（中階）                NaN
1909958      9           4月特別任務－【SDGs 議題】（中階）                NaN

        mission_field mission_type  mission_semester_year mission_semester  \
1909956            議題          非連續                    112            112-2
1909957           NaN          NaN                    112            112-2
1909958           NaN          NaN                    112            112-2

                mission_datetime_utc8 mission_status  is_completed  ...  \
1909956  Mon Apr 22 08:00:00 UTC 2024          已派發任務             0  ...
1909957  Mon Apr 22 08:00:00 UTC 2024          已派發任務             0  ...
1909958  Mon Apr 22 08:00:00 UTC 2024          已派發任務             0  ...

        answer_duration_sec  mission_answer_count  \
1909956                 NaN                     0
1909957                 NaN                     0
1909958                 NaN                     0

         content_indicator_correct_rate  comprehensive_indicator_correct_rate  \
1909956                             NaN                                   NaN
1909957                             NaN                                   NaN
1909958                             NaN                                   NaN

         explanation_indicator_correct_rate  \
1909956                                 NaN
1909957                                 NaN
1909958                                 NaN

         extraction_indicator_correct_rate  form_indicator_correct_rate  \
1909956                                NaN                          NaN
1909957                                NaN                          NaN
1909958                                NaN                          NaN

         first_correct_rate              user_id          mission_id
1909956                 NaN -3633088233029289359  703618323232836566
1909957                 NaN -3198336096824660439 -371611706378504607
1909958                 NaN  8248998181802054321 -371611706378504607

[3 rows x 22 columns]
RangeIndex(start=0, stop=1909959, step=1)
Index(['grade', 'mission_name', 'mission_difficulty', 'mission_field',
       'mission_type', 'mission_semester_year', 'mission_semester',
       'mission_datetime_utc8', 'mission_status', 'is_completed',
       'completed_at_utc8', 'correct_rate', 'answer_duration_sec',
       'mission_answer_count', 'content_indicator_correct_rate',
       'comprehensive_indicator_correct_rate',
       'explanation_indicator_correct_rate',
       'extraction_indicator_correct_rate', 'form_indicator_correct_rate',
       'first_correct_rate', 'user_id', 'mission_id'],
      dtype='object')

export ny data to my computer

In [13]:
a = df2.columns
a_series = a.to_series()
print(a_series)
a_series.to_csv('work1.csv', index = False)

grade                                                                  grade
mission_name                                                    mission_name
mission_difficulty                                        mission_difficulty
mission_field                                                  mission_field
mission_type                                                    mission_type
mission_semester_year                                  mission_semester_year
mission_semester                                            mission_semester
mission_datetime_utc8                                  mission_datetime_utc8
mission_status                                                mission_status
is_completed                                                    is_completed
completed_at_utc8                                          completed_at_utc8
correct_rate                                                    correct_rate
answer_duration_sec                                      answer_duration_sec
mission_answer_count                                    mission_answer_count
content_indicator_correct_rate                content_indicator_correct_rate
comprehensive_indicator_correct_rate    comprehensive_indicator_correct_rate
explanation_indicator_correct_rate        explanation_indicator_correct_rate
extraction_indicator_correct_rate          extraction_indicator_correct_rate
form_indicator_correct_rate                      form_indicator_correct_rate
first_correct_rate                                        first_correct_rate
user_id                                                              user_id
mission_id                                                        mission_id
dtype: object

了解資料型態

In [15]:
 df2.describe()

,grade,mission_semester_year,is_completed,correct_rate,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
count,1.909959e+06,1909959.0,1.909959e+06,454877.000000,453620.000000,1.909959e+06,106038.000000,448856.000000,392142.000000,414331.000000,78801.000000,473392.000000,1.909959e+06,1.909959e+06
mean,5.949924e+00,112.0,2.381606e-01,0.412165,147.150187,7.111859e-01,0.377652,0.414174,0.385411,0.438963,0.375179,0.451405,-5.836128e+15,-1.368036e+17
std,1.586873e+00,0.0,4.259580e-01,0.317815,328.610611,1.676427e+00,0.475326,0.401837,0.446032,0.455068,0.482087,0.316127,5.341203e+18,5.285432e+18
min,4.000000e+00,112.0,0.000000e+00,0.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-9.223321e+18,-9.144214e+18
25%,5.000000e+00,112.0,0.000000e+00,0.200000,10.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,-4.611004e+18,-4.782878e+18
50%,6.000000e+00,112.0,0.000000e+00,0.400000,37.000000,0.000000e+00,0.000000,0.333333,0.000000,0.333333,0.000000,0.400000,6.201597e+16,-2.337655e+17
75%,7.000000e+00,112.0,0.000000e+00,0.600000,176.000000,1.000000e+00,1.000000,0.857143,1.000000,1.000000,1.000000,0.600000,4.565403e+18,3.909487e+18
max,9.000000e+00,112.0,1.000000e+00,1.000000,3600.000000,2.100000e+02,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,9.218903e+18,9.217426e+18

export data in excel pattern

In [17]:
b = df2.describe()
print(b)
b.to_excel('work2.xlsx')

              grade  mission_semester_year  is_completed   correct_rate  \
count  1.909959e+06              1909959.0  1.909959e+06  454877.000000
mean   5.949924e+00                  112.0  2.381606e-01       0.412165
std    1.586873e+00                    0.0  4.259580e-01       0.317815
min    4.000000e+00                  112.0  0.000000e+00       0.000000
25%    5.000000e+00                  112.0  0.000000e+00       0.200000
50%    6.000000e+00                  112.0  0.000000e+00       0.400000
75%    7.000000e+00                  112.0  0.000000e+00       0.600000
max    9.000000e+00                  112.0  1.000000e+00       1.000000

       answer_duration_sec  mission_answer_count  \
count        453620.000000          1.909959e+06
mean            147.150187          7.111859e-01
std             328.610611          1.676427e+00
min               1.000000          0.000000e+00
25%              10.000000          0.000000e+00
50%              37.000000          0.000000e+00
75%             176.000000          1.000000e+00
max            3600.000000          2.100000e+02

       content_indicator_correct_rate  comprehensive_indicator_correct_rate  \
count                   106038.000000                         448856.000000
mean                         0.377652                              0.414174
std                          0.475326                              0.401837
min                          0.000000                              0.000000
25%                          0.000000                              0.000000
50%                          0.000000                              0.333333
75%                          1.000000                              0.857143
max                          1.000000                              1.000000

       explanation_indicator_correct_rate  extraction_indicator_correct_rate  \
count                       392142.000000                      414331.000000
mean                             0.385411                           0.438963
std                              0.446032                           0.455068
min                              0.000000                           0.000000
25%                              0.000000                           0.000000
50%                              0.000000                           0.333333
75%                              1.000000                           1.000000
max                              1.000000                           1.000000

       form_indicator_correct_rate  first_correct_rate       user_id  \
count                 78801.000000       473392.000000  1.909959e+06
mean                      0.375179            0.451405 -5.836128e+15
std                       0.482087            0.316127  5.341203e+18
min                       0.000000            0.000000 -9.223321e+18
25%                       0.000000            0.200000 -4.611004e+18
50%                       0.000000            0.400000  6.201597e+16
75%                       1.000000            0.600000  4.565403e+18
max                       1.000000            1.000000  9.218903e+18

         mission_id
count  1.909959e+06
mean  -1.368036e+17
std    5.285432e+18
min   -9.144214e+18
25%   -4.782878e+18
50%   -2.337655e+17
75%    3.909487e+18
max    9.217426e+18

data sort<br>
df.sort_index(axis=1, ascending=False)<br>
意義(<br>
  axix 0:排序欄<br>
  axis 1:排序列<br>
  ascending = True:升序排列<br>
  ascending = False:降序排列<br>
  )<br>

In [20]:
b.sort_index(axis=1, ascending=False)

,user_id,mission_semester_year,mission_id,mission_answer_count,is_completed,grade,form_indicator_correct_rate,first_correct_rate,extraction_indicator_correct_rate,explanation_indicator_correct_rate,correct_rate,content_indicator_correct_rate,comprehensive_indicator_correct_rate,answer_duration_sec
count,1.909959e+06,1909959.0,1.909959e+06,1.909959e+06,1.909959e+06,1.909959e+06,78801.000000,473392.000000,414331.000000,392142.000000,454877.000000,106038.000000,448856.000000,453620.000000
mean,-5.836128e+15,112.0,-1.368036e+17,7.111859e-01,2.381606e-01,5.949924e+00,0.375179,0.451405,0.438963,0.385411,0.412165,0.377652,0.414174,147.150187
std,5.341203e+18,0.0,5.285432e+18,1.676427e+00,4.259580e-01,1.586873e+00,0.482087,0.316127,0.455068,0.446032,0.317815,0.475326,0.401837,328.610611
min,-9.223321e+18,112.0,-9.144214e+18,0.000000e+00,0.000000e+00,4.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,-4.611004e+18,112.0,-4.782878e+18,0.000000e+00,0.000000e+00,5.000000e+00,0.000000,0.200000,0.000000,0.000000,0.200000,0.000000,0.000000,10.000000
50%,6.201597e+16,112.0,-2.337655e+17,0.000000e+00,0.000000e+00,6.000000e+00,0.000000,0.400000,0.333333,0.000000,0.400000,0.000000,0.333333,37.000000
75%,4.565403e+18,112.0,3.909487e+18,1.000000e+00,0.000000e+00,7.000000e+00,1.000000,0.600000,1.000000,1.000000,0.600000,1.000000,0.857143,176.000000
max,9.218903e+18,112.0,9.217426e+18,2.100000e+02,1.000000e+00,9.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3600.000000

Getitem<br>
練習a column 的[0:3]

In [27]:
 print(df2["user_id"])
 print(df2[0:3])
 df2["user_id"][0:3]

0         -8373966078912715601
1          3516683932418412104
2           -65799051578279613
3         -6293485111595748020
4          4998280410504838977
                  ...
1909954    5090607127449525741
1909955    1122720388891184818
1909956   -3633088233029289359
1909957   -3198336096824660439
1909958    8248998181802054321
Name: user_id, Length: 1909959, dtype: int64
   grade                mission_name mission_difficulty mission_field  \
0      5  05/06 虎姑婆【多元文化教育－傳說故事】（初階）                  易            文學
1      5   05/06 二郎【多元文化教育－傳說故事】（初階）                  中            文學
2      6   05/09 蚩尤【多元文化教育－傳說故事】（初階）                  難            人物

  mission_type  mission_semester_year mission_semester  \
0           連續                    112            112-2
1           連續                    112            112-2
2           連續                    112            112-2

          mission_datetime_utc8 mission_status  is_completed  ...  \
0  Mon May 06 08:00:00 UTC 2024          已派發任務             0  ...
1  Mon May 06 08:00:00 UTC 2024          已派發任務             0  ...
2  Thu May 09 08:00:00 UTC 2024          已派發任務             0  ...

  answer_duration_sec  mission_answer_count  content_indicator_correct_rate  \
0                 NaN                     0                             NaN
1                 NaN                     0                             NaN
2                 NaN                     0                             NaN

   comprehensive_indicator_correct_rate  explanation_indicator_correct_rate  \
0                                   NaN                                 NaN
1                                   NaN                                 NaN
2                                   NaN                                 NaN

   extraction_indicator_correct_rate  form_indicator_correct_rate  \
0                                NaN                          NaN
1                                NaN                          NaN
2                                NaN                          NaN

   first_correct_rate              user_id           mission_id
0                 NaN -8373966078912715601  8154604467375388289
1                 NaN  3516683932418412104  3762301478342295221
2                 NaN   -65799051578279613  4652807748946159405

[3 rows x 22 columns]

0   -8373966078912715601
1    3516683932418412104
2     -65799051578279613
Name: user_id, dtype: int64

###重複資料

1.*查詢重複數值的個數*<br>
(標記並列出重複的行)<br>
(.sum統計次數)

In [28]:
a = 'grade'
df2.duplicated(subset=[a]).sum()

1909953

2.列出

In [29]:
 duplication = df2[df2.duplicated(a)]
 duplication[a]

1          5
3          5
4          6
5          6
6          5
          ..
1909954    8
1909955    8
1909956    8
1909957    8
1909958    9
Name: grade, Length: 1909953, dtype: int64

3.處理(刪除遺失值)

In [30]:
 a = 'user_id'
 df3 = df2.drop_duplicates(a)
 df3

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8373966078912715601,8154604467375388289
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3516683932418412104,3762301478342295221
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-65799051578279613,4652807748946159405
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6293485111595748020,240621445882253268
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4998280410504838977,-3340858198738005072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024467,4,01/15 運動中心傳單【生命教育－運動鍛鍊】(初階),中,說明文件,非連續,112,112-1,Mon Jan 15 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-4922170724652889514,5050648008685985453
1024468,4,01/15 關於跳躍力的祕密【生命教育－運動鍛鍊】(初階),易,生活知識,連續,112,112-1,Mon Jan 15 08:00:00 UTC 2024,進行任務中,0,...,NaN,2,NaN,NaN,NaN,NaN,NaN,0.6,-2434296012334180512,4447409378859886590
1140603,7,01/15 VR把你放進別人的鞋裡？！【科技教育－現代科技】(中階),中,議題,連續,112,112-1,Mon Jan 15 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-2023147156830779559,6244252628695738548
1167646,4,06/27 紙【能源教育－環境保育】（初階）,易,生活知識,連續＋圖表,112,112-2,Thu Jun 27 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-3850367010299798424,6001971291541386821
1460810,7,01/15 VR把你放進別人的鞋裡？！【科技教育－現代科技】(中階),中,議題,連續,112,112-1,Mon Jan 15 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4004540051063081003,6244252628695738548

###次數分配表

1.變化

In [35]:
df2.groupby("user_id").sum()

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,correct_rate,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,mission_id
user_id,,,,,,,,,,,,,,,,,,,,,
-9223321156357508358,1190,04/11 仲裁【法治教育－法律程序】（中階）06/13 強迫愛心的愛心筆【法治教育－買賣相...,難難易中中中易中難中中中中難中中易中易中中難中易易中難中易中中中中中中易中中中中難中中中難中...,議題生活知識自然科學議題人文史地社會科學社會科學議題議題人文史地文化社會科學議題生活知識人文...,連續連續連續連續連續連續連續連續連續連續連續連續連續非連續連續＋圖表連續連續＋圖表連續連續連...,19040,112-2112-2112-2112-1112-1112-1112-1112-1112-11...,Thu Apr 11 08:00:00 UTC 2024Thu Jun 13 08:00:0...,完成任務完成任務已派發任務完成任務完成任務完成任務完成任務完成任務完成任務完成任務完成任務完...,160,...,47.866667,18586.0,383,12.5,48.361111,30.833333,46.833333,4.0,103.266667,-1926107515567539009
-9222609255196723390,516,11/13 叮叮車【國際教育－各國特色】(初階)11/30 臺灣的斑比們──臺灣原生鹿種【環...,中中中中中中中易中中中難易易中易中中易易中中中易易易中易中中難中中易易難中中中易難中難難中中...,世界櫥窗自然科學議題議題世界櫥窗文化自然科學自然科學社會科學生活知識生活知識議題文化生活知識...,連續＋圖表連續非連續連續連續連續＋圖表非連續連續連續連續連續連續連續連續非連續連續連續連續連...,9632,112-1112-1112-1112-1112-1112-1112-1112-1112-11...,Mon Nov 13 08:00:00 UTC 2023Thu Nov 30 08:00:0...,已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已...,0,...,0.000000,0.0,2,0.0,0.000000,0.000000,0.000000,0.0,1.000000,-7325070470043933918
-9221920182052420668,1521,01/15 睡眠數據機【科技教育－現代科技】(中階)02/15 兒童文學【閱讀素養教育－以文...,中易中中難中難難難難中中難中易中易中中難易中中中中難中難中易中中易難中易中易易易中中中易中難...,生活知識文學說明文件人文史地世界櫥窗議題議題說明文件生活知識生活知識議題人文史地人文史地人文...,連續連續非連續連續連續連續連續非連續連續連續＋圖表連續＋圖表連續連續連續連續連續連續連續連續...,18928,112-1112-2112-2112-2112-2112-2112-2112-2112-21...,Mon Jan 15 08:00:00 UTC 2024Thu Feb 15 08:00:0...,已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已...,14,...,11.533333,3414.0,28,3.0,10.607143,11.333333,10.500000,1.0,12.533333,7218106719364151143
-9221135146560186179,1530,02/26 公車事故檢討報告【生命教育－生活常識】（中階）04/08 存證信函【法治教育－法...,中中中易易難中易中中易難難中中中中中中中中難易中中難中中難中易中難中易中難中中易中難中難中中...,說明文件生活知識自然科學自然科學世界櫥窗人文史地社會科學社會科學議題議題生活知識自然科學世界...,非連續連續連續連續＋圖表連續連續＋圖表連續連續連續連續非連續非連續連續連續連續非連續連續＋圖...,19040,112-2112-2112-2112-2112-2112-2112-2112-2112-21...,Mon Feb 26 08:00:00 UTC 2024Mon Apr 08 08:00:0...,已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已...,14,...,0.000000,64.0,35,0.0,0.000000,0.000000,0.000000,0.0,13.200000,-1926107515567539009
-9221071331548492145,1360,09/07 崑崙奴【人權教育－勞動權益】（中階）9月特別任務－【SDGs 議題】（中階）10...,中易中易易中難中難中易中難難易易易難難難易易中難中中中易中易易中中中易中中中中中難難中中易難...,人文史地自然科學人文史地議題說明文件社會科學社會科學議題議題生活知識文化議題生活知識議題自然...,連續連續連續連續非連續連續連續連續連續非連續連續連續非連續連續連續＋圖表連續連續＋圖表非連續...,19040,112-1112-1112-1112-1112-1112-1112-1112-1112-11...,Thu Sep 07 08:00:00 UTC 2023Fri Sep 22 08:00:0...,已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已...,7,...,1.800000,98.0,37,1.0,2.833333,0.500000,2.000000,0.0,2.600000,-1926107515567539009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9212461263078797593,1190,04/25 森林中的播種者：月熊【環境教育－動物保育】（中階）04/29 誰是莎士比亞？【多...,易中中易難中中中易難中中中中難中難易易中中中中中中易難中中易中難難中中中中難中中中易中中易易...,自然科學人物人物生活知識生活知識人文史地議題議題生活知識世界櫥窗文學議題議題說明文件生活知識...,連續連續連續連續＋圖表非連續連續連續＋圖表連續非連續連續連續連續連續非連續連續連續連續連續連...,19040,112-2112-2112-2112-2112-2112-2112-1112-1112-11...,Thu Apr 25 08:00:00 UTC 2024Mon Apr 29 08:00:0...,已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已...,0,...,0.000000,0.0,2,0.0,0.000000,0.000000,0.000000,0.0,0.600000,-1926107515567539009
9212946253008955797,1530,10/09 行道樹 打造都市美感與新生態【環境教育－植物生態】（中階）10/30 戰火下的千...,中中易易中易難中中難中中中難中難難易中中難中中中中中中難難中中易難易中易難易中中易中難難中難...,人文史地世界櫥窗人文史地世界櫥窗文化社會科學議題議題生活知識說明文件人文史地文化生活知識議題...,連續連續連續非連續連續連續連續連續連續連續＋圖表非連續連續＋圖表連續連續連續非連續連續連續＋...,19040,112-1112-1112-1112-1112-1112-1112-1112-1112-11...,Mon Oct 09 08:00:00 UTC 2023Mon Oct 30 08:00:0...,已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已...,4,...,1.800000,774.0,9,2.0,1.500000,1.333333,2.000000,0.0,2.200000,-1926107515567539009
9215839480821721378,332,02/19 出遊計畫【生命教育－校園生活】（初階）02/19 校外教學學習單【生命教育－校園...,易易中難中中中難易中易中中中中中中中中中中中易中中易中中易中易中中中中中中中易易中易易易中難...,說明文件生活知識議題人文史地生活知識生活知識世界櫥窗文學生活知識自然科學生活知識人文史地世界...,非連續非連續非連續連續非連續非連續非連續連續非連續連續連續＋圖表連續連續連續非連續非連續非連...,9296,112-2112-2112-2112-2112-2112-2112-2112-2112-21...,Mon Feb 19 08:00:00 UTC 2024Mon Feb 19 08:00:0...,已派發任務已派發任務已派發任務完成任務已派發任務已派發任務已派發任務已派發任務已派發任務完成...,22,...,13.466667,481.0,38,2.0,13.888889,11.000000,13.766667,2.0,13.133333,-7078261163371424102
9216205039327361044,845,06/20 未來肉【多元文化教育－飲食文化】（初階）11/16 回收物的去向【環境教育－環境...,易中易中易難中中中易中難中難中中中易易易中易難易中難中中難易易中易易中易易中易中中中易中中難...,生活知識生活知識自然科學生活知識議題文學文化議題生活知識社會科學世界櫥窗議題自然科學自然科學...,非連續非連續連續非連續連續連續連續非連續非連續連續連續＋圖表連續非連續連續＋圖表非連續非連續...,18928,112-2112-1112-1112-1112-1112-1112-1112-2112-21...,Thu Jun 20 08:00:00 UTC 2024Thu Nov 16 08:00:0...,已派發任務已派發任務已派發任務已派發任務完成任務完成任務完成任務已派發任務完成任務已派發任務...,105,...,29.000000,4324.0,395,8.0,30.666667,23.166667,22.333333,7.0,31.000000,4043412440294193596
9218903231836064997,1014,4月特別任務－【SDGs 議題】（初階）05/20 揚州炒飯【多元文化教育－異國美食】（初階...,中易中中中中中難中中難中中中難中中易中難中易難易中難中難中易易易中中易中中中中中易中中中易難...,文化生活知識人文史地人物文化文化自然科學世界櫥窗議題議題生活知識生活知識議題說明文件文化說明...,連續非連續連續連續非連續連續＋圖表連續＋圖表非連續連續連續連續非連續非連續非連續連續非連續連...,18928,112-2112-2112-2112-1112-1112-1112-1112-1112-11...,Mon Apr 22 08:00:00 UTC 2024Mon May 20 08:00:0...,已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已派發任務已...,21,...,6.000000,451.0,57,1.0,4.250000,6.000000,5.000000,3.0,7.400000,4043412440294193596

In [36]:
stack = df.stack()
stack

0        grade                                            5
         mission_name            05/06 虎姑婆【多元文化教育－傳說故事】（初階）
         mission_difficulty                               易
         mission_field                                   文學
         mission_type                                    連續
                                            ...
1909958  mission_status                               已派發任務
         is_completed                                     0
         mission_answer_count                             0
         user_id                        8248998181802054321
         mission_id                     -371611706378504607
Length: 27836071, dtype: object

次數分配表

In [45]:
a = df2.columns
pp2 = []
for j in a:
  try:
    print(df2[j].groupby(df2[j]).count())
    pp2.append(df2[j].groupby(df2[j]).count())
  except:
    print("KeyError")

grade
4    428520
5    438802
6    397674
7    265140
8    204410
9    175413
Name: grade, dtype: int64
mission_name
01/01 我們是用戶還是商品？社群媒體之戰【資訊教育－社群媒體】(中階)     4043
01/01 數據風暴【資訊教育－社群媒體】(中階)                 4043
01/01 表情符號【資訊教育－資訊解讀】(初階)                 7608
01/01 觀影資訊【資訊教育－資訊解讀】(初階)                 7608
01/04 你可能已經犯罪了！【資訊教育－數位倫理】(中階)            4046
                                         ...
5月特別任務－【SDGs 議題】（初階）                      7318
6月特別任務－【SDGs 議題】（中階）                      3711
6月特別任務－【SDGs 議題】（初階）                      7324
9月特別任務－【SDGs 議題】（中階）                     11760
9月特別任務－【SDGs 議題】（初階）                     22647
Name: mission_name, Length: 335, dtype: int64
mission_difficulty
中    1030200
易     487585
難     302401
Name: mission_difficulty, dtype: int64
mission_field
世界櫥窗    198882
人文史地    169453
人物       79521
文化      150953
文學       78925
生活知識    449538
社會科學     98284
自然科學    212554
說明文件     81762
議題      300314
Name: mission_field, dtype: int64
mission_type
連續       1047541
連續＋圖表     227882
非連續       544763
Name: mission_type, dtype: int64
mission_semester_year
112    1909959
Name: mission_semester_year, dtype: int64
mission_semester
112-1    994821
112-2    915138
Name: mission_semester, dtype: int64
mission_datetime_utc8
Fri Dec 22 08:00:00 UTC 2023    11645
Fri Mar 22 08:00:00 UTC 2024    10972
Fri Sep 22 08:00:00 UTC 2023    34407
Mon Apr 01 08:00:00 UTC 2024    21958
Mon Apr 08 08:00:00 UTC 2024    21970
                                ...
Thu Sep 14 08:00:00 UTC 2023    22868
Thu Sep 21 08:00:00 UTC 2023    22902
Thu Sep 28 08:00:00 UTC 2023    23022
Wed May 22 08:00:00 UTC 2024    11016
Wed Nov 22 08:00:00 UTC 2023    11624
Name: mission_datetime_utc8, Length: 86, dtype: int64
mission_status
取消派發        3230
完成任務      453812
已派發任務    1406948
暫停任務       39636
進行任務中       6333
Name: mission_status, dtype: int64
is_completed
0    1455082
1     454877
Name: is_completed, dtype: int64
completed_at_utc8
Fri Apr 05 07:10:18 UTC 2024    1
Fri Apr 05 07:44:10 UTC 2024    1
Fri Apr 05 07:51:52 UTC 2024    1
Fri Apr 05 07:52:32 UTC 2024    1
Fri Apr 05 07:53:22 UTC 2024    1
                               ..
Wed Sep 27 22:50:10 UTC 2023    1
Wed Sep 27 23:01:33 UTC 2023    1
Wed Sep 27 23:06:18 UTC 2023    1
Wed Sep 27 23:11:05 UTC 2023    1
Wed Sep 27 23:20:47 UTC 2023    1
Name: completed_at_utc8, Length: 389446, dtype: int64
correct_rate
0.000000     80825
0.066667      1579
0.133333      2786
0.166667         2
0.200000    107767
0.266667      4079
0.300000         1
0.333333      3120
0.400000     94870
0.466667      1209
0.500000         1
0.533333       733
0.600000     61405
0.666667       327
0.733333       260
0.800000     43527
0.866667       199
0.933333       156
1.000000     52031
Name: correct_rate, dtype: int64
answer_duration_sec
1.0         387
2.0        1067
3.0        4240
4.0       10497
5.0       16398
          ...
3556.0        1
3585.0        1
3598.0        1
3599.0       40
3600.0     2291
Name: answer_duration_sec, Length: 2260, dtype: int64
mission_answer_count
0      1423375
1       105920
2       189753
3        87974
4        41945
        ...
94           1
95           1
113          1
117          1
210          1
Name: mission_answer_count, Length: 69, dtype: int64
content_indicator_correct_rate
0.0    64063
0.5     3859
1.0    38116
Name: content_indicator_correct_rate, dtype: int64
comprehensive_indicator_correct_rate
0.000000    177720
0.111111      1049
0.125000       597
0.142857      1469
0.166667       226
0.200000      1185
0.222222      1296
0.250000      7890
0.285714      1525
0.333333     39670
0.375000       436
0.400000       843
0.428571      1004
0.444444       635
0.500000     70348
0.555556       332
0.571429       488
0.600000       367
0.625000       101
0.666667     25438
0.714286       231
0.750000      3433
0.777778       141
0.800000       123
0.833333        20
0.857143       144
0.875000        40
0.888889       101
1.000000    112004
Name: comprehensive_indicator_correct_rate, dtype: int64
explanation_indicator_correct_rate
0.000000    209054
0.166667      1112
0.200000       194
0.250000       808
0.333333      7409
0.400000       201
0.500000     47586
0.600000       125
0.666667      3904
0.750000       129
0.800000        93
0.833333        54
1.000000    121473
Name: explanation_indicator_correct_rate, dtype: int64
extraction_indicator_correct_rate
0.000000    196367
0.166667       569
0.200000      2839
0.250000      1919
0.333333      7147
0.400000      2080
0.500000     48017
0.600000       947
0.666667      3888
0.750000       451
0.800000       418
0.833333        67
1.000000    149622
Name: extraction_indicator_correct_rate, dtype: int64
form_indicator_correct_rate
0.0    48919
0.5      635
1.0    29247
Name: form_indicator_correct_rate, dtype: int64
first_correct_rate
0.000000     59547
0.066667       970
0.133333      2239
0.200000    115451
0.266667      3689
0.333333      2903
0.400000    103241
0.466667      1156
0.500000         1
0.533333       710
0.600000     67423
0.666667       325
0.700000         1
0.733333       256
0.800000     51153
0.866667       197
0.933333       154
1.000000     63976
Name: first_correct_rate, dtype: int64
user_id
-9223321156357508358    170
-9222609255196723390     86
-9221920182052420668    169
-9221135146560186179    170
-9221071331548492145    170
                       ...
 9212461263078797593    170
 9212946253008955797    170
 9215839480821721378     83
 9216205039327361044    169
 9218903231836064997    169
Name: user_id, Length: 11607, dtype: int64
mission_id
-9144214234931690152    3230
-9108400203314660527    7303
-9027191344670616678    7593
-9015409752689176971    4043
-8952441151237813732    3954
                        ...
 9100905062053433045    7528
 9118852782984091913    7308
 9122207813419383599    3879
 9180294589109158089    7287
 9217425772124953331    7592
Name: mission_id, Length: 339, dtype: int64

Export result<br>
#
*輸出 次數分配表到筆記本*

In [48]:
with open('次數table_3.txt', 'w', encoding = 'utf-8') as f:
  f.write(str(pp2))
  f.close

處理

#
*interpolate’s parameter: "ffill", "bfill", "pad", "backfill"*

In [50]:
 df2.dropna()
 df2.fillna(5)
 df2.interpolate()

<ipython-input-50-63ffd59540da>:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df2.interpolate()

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,answer_duration_sec,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id
0,5,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-8373966078912715601,8154604467375388289
1,5,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,3516683932418412104,3762301478342295221
2,6,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-65799051578279613,4652807748946159405
3,5,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,-6293485111595748020,240621445882253268
4,6,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,4998280410504838977,-3340858198738005072
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909954,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,5090607127449525741,703618323232836566
1909955,8,04/22 人與鼠的戰爭【環境教育－動物保育】（中階）,易,世界櫥窗,連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,1122720388891184818,8809938774431070893
1909956,8,04/22 動物園該存在嗎？【環境教育－動物保育】（中階）,難,議題,非連續,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,-3633088233029289359,703618323232836566
1909957,8,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,-3198336096824660439,-371611706378504607
1909958,9,4月特別任務－【SDGs 議題】（中階）,NaN,NaN,NaN,112,112-2,Mon Apr 22 08:00:00 UTC 2024,已派發任務,0,...,102.0,0,0.0,0.0,0.5,0.0,1.0,0.2,8248998181802054321,-371611706378504607

###Data combine

contact()

In [64]:
 df1 = pd.DataFrame(
     {
         "A": ["A0", "A1", "A2", "A3"],"B": ["B0", "B1", "B2", "B3"], "C": ["C0", "C1", "C2", "C3"], "D": ["D0", "D1", "D2", "D3"],
     },
      index=[0, 1, 2, 3],
 )
 df2 = pd.DataFrame(
     {
          "A": ["A4", "A5", "A6", "A7"], "B": ["B4", "B5", "B6", "B7"], "C": ["C4", "C5", "C6", "C7"], "D": ["D4", "D5", "D6", "D7"],
     },
      index=[0, 1, 2, 3],
 )
 df3 = pd.DataFrame(
     {
          "A": ["A8", "A9", "A10", "A11"], "B": ["B8", "B9", "B10", "B11"], "C": ["C8", "C9", "C10", "C11"], "D": ["D8", "D9", "D10", "D11"],
     },
      index=[0, 1, 2, 3],
 )

contact

In [59]:
frames = [df1, df2, df3]
result = pd.concat(frames)
result

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

join

In [60]:
df4 = pd.DataFrame(
  {
    "B": ["B2", "B3", "B6", "B7"],
    "D": ["D2", "D3", "D6", "D7"],
    "F": ["F2", "F3", "F6", "F7"],
  },
  index=[2, 3, 6, 7],
)
result = pd.concat([df1, df4], axis=1)

result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

merge

In [65]:
# {} indicate that data frame is 字典
left = pd.DataFrame({"key": ["A","B"], "lval": [1,2]})
print(left)
right = pd.DataFrame({"key": ["A","B"], "rval": [3,4]})
print(right)
# according to the condition of key to merge
pd.merge(right, left, on="key")

  key  lval
0   A     1
1   B     2
  key  rval
0   A     3
1   B     4

  key  rval  lval
0   A     3     1
1   B     4     2

###Homework

In [71]:
 gf= []
 ww= df['grade']
 for i in range(len(ww)):
  i+= 1
  gf.append(i)
 df4 = pd.DataFrame(gf)
 df4

frames = [dfhw, df4]
result = pd.concat(frames)
result

,grade,mission_name,mission_difficulty,mission_field,mission_type,mission_semester_year,mission_semester,mission_datetime_utc8,mission_status,is_completed,...,mission_answer_count,content_indicator_correct_rate,comprehensive_indicator_correct_rate,explanation_indicator_correct_rate,extraction_indicator_correct_rate,form_indicator_correct_rate,first_correct_rate,user_id,mission_id,0
0,5.0,05/06 虎姑婆【多元文化教育－傳說故事】（初階）,易,文學,連續,112.0,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-8.373966e+18,8.154604e+18,NaN
1,5.0,05/06 二郎【多元文化教育－傳說故事】（初階）,中,文學,連續,112.0,112-2,Mon May 06 08:00:00 UTC 2024,已派發任務,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,3.516684e+18,3.762301e+18,NaN
2,6.0,05/09 蚩尤【多元文化教育－傳說故事】（初階）,難,人物,連續,112.0,112-2,Thu May 09 08:00:00 UTC 2024,已派發任務,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-6.579905e+16,4.652808e+18,NaN
3,5.0,05/13 狗狗吃便便【環境教育－動物奇聞】（初階）,中,生活知識,非連續,112.0,112-2,Mon May 13 08:00:00 UTC 2024,已派發任務,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,-6.293485e+18,2.406214e+17,NaN
4,6.0,05/16 白蟻跟你想像的不一樣！【環境教育－動物奇聞】（初階）,易,自然科學,連續＋圖表,112.0,112-2,Thu May 16 08:00:00 UTC 2024,已派發任務,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,4.998280e+18,-3.340858e+18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909954,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909955.0
1909955,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909956.0
1909956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909957.0
1909957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909958.0
1909958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1909959.0